version: '3.8'
services:
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    
  shorturl:
    build: .
    ports:
      - '8000:8000'
    environment:
      - DB_NAME=db
      - DB_HOST=mongodb
      - DB_PORT=27017
      - BASE_URL=http://localhost:8000
    depends_on:
      - mongodb
  shorturl2:
    build: .
    ports:
      - '8020:8000'
    environment:
      - DB_NAME=db
      - DB_HOST=mongodb
      - DB_PORT=27017
      - BASE_URL=http://localhost:8080
    depends_on:
      - mongodb
volumes:
  dbdata6: